//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class eve_map_solarsystem_jumps
    {
        public int from_solarsystem_id { get; set; }
        public int to_solarsystem_id { get; set; }
        public int from_region_id { get; set; }
        public int to_region_id { get; set; }
    }
}
