//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class eve_map_solarsystems
    {
        public int solarsystem_id { get; set; }
        public Nullable<int> region_id { get; set; }
        public string region_name { get; set; }
        public string solarsystem_name { get; set; }
        public Nullable<double> security { get; set; }
        public Nullable<long> x { get; set; }
        public Nullable<long> y { get; set; }
        public Nullable<long> z { get; set; }
        public Nullable<short> flat_x { get; set; }
        public Nullable<short> flat_y { get; set; }
        public Nullable<int> dotlan_x { get; set; }
        public Nullable<int> dotlan_y { get; set; }
        public Nullable<bool> has_station { get; set; }
    }
}
