//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class eve_inv_types
    {
        public int type_id { get; set; }
        public Nullable<int> marketgroup_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string group_name { get; set; }
        public string faction { get; set; }
        public short meta_level { get; set; }
        public Nullable<int> graphic_id { get; set; }
        public string icon_name { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> volume_assembled { get; set; }
        public Nullable<int> portion_size { get; set; }
        public Nullable<int> race_id { get; set; }
        public Nullable<bool> published { get; set; }
        public Nullable<bool> is_npc_sell { get; set; }
        public Nullable<bool> is_npc_buy { get; set; }
        public Nullable<double> jita_price_sell { get; set; }
        public Nullable<double> jita_price_buy { get; set; }
        public Nullable<long> jita_qty_30 { get; set; }
        public Nullable<System.DateTime> jita_date { get; set; }
        public Nullable<double> C5pct_price_sell { get; set; }
        public Nullable<double> C5pct_price_buy { get; set; }
        public Nullable<System.DateTime> C5pct_date { get; set; }
        public System.DateTime updated { get; set; }
    }
}
