//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Entity
{
	using System;
	using System.Linq;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	[DbConfigurationType(typeof(MySql.Data.Entity.MySqlEFConfiguration))]
	public partial class EntitiesConnection : DbContext
    {
        public EntitiesConnection()
            : base("name=EntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<eve_inv_marketgroups> eve_inv_marketgroups { get; set; }
        public DbSet<eve_inv_types> eve_inv_types { get; set; }
        public DbSet<eve_map_regions> eve_map_regions { get; set; }
        public DbSet<eve_map_solarsystems> eve_map_solarsystems { get; set; }
    }
}
