//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [DbConfigurationType(typeof(MySql.Data.Entity.MySqlEFConfiguration))]
    public partial class sysEntities : DbContext
    {
        public sysEntities()
            : base("name=sysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eve_inv_marketgroups> eve_inv_marketgroups { get; set; }
        public virtual DbSet<eve_inv_types> eve_inv_types { get; set; }
        public virtual DbSet<eve_map_regions> eve_map_regions { get; set; }
        public virtual DbSet<eve_map_solarsystem_jumps> eve_map_solarsystem_jumps { get; set; }
        public virtual DbSet<eve_map_solarsystems> eve_map_solarsystems { get; set; }
        public virtual DbSet<eve_sta_stations> eve_sta_stations { get; set; }
        public virtual DbSet<sys_config> sys_config { get; set; }
    }
}
