//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_config
    {
        public string variable { get; set; }
        public string value { get; set; }
        public System.DateTime set_time { get; set; }
        public string set_by { get; set; }
    }
}
